### ISSUE TITLE
If I want to use Essential, how should I do it❓ 

### ISSUE THREAD

**Issue by trbozo** [totigm/twitter-crypto-bot#30]
Whenever I run the application I get this error. If I want to use Essential, how should I do it?

You currently have Essential access which includes access to Twitter API v2 endpoints only. If you need access to this endpoint, you’ll need to apply for Elevated access via the Developer Portal. You can learn more here: https://developer.twitter.com/en/docs/twitter-api/getting-started/about-twitter-api#v2-access-leve

**Comment by totigm** [comment]
Hey @trbozo! How are you doing?

Sorry for the delay.

This project uses the [twit NPM package](https://www.npmjs.com/package/twit), which uses the Twitter API v1.
I don't know too much about the new version accesses, but it seems like you only have access to v2, and not to v1. You'll need to apply for access to v1 in order to use this project.

When we developed this project, the Twitter API v2 hadn't been released yet, so we used v1. At least for now, we are not planning to refactor it for v2.

I hope that helps!
