### ISSUE TITLE
hasHashtags is not working❓ 

### ISSUE THREAD

**Issue by trbozo** [totigm/twitter-crypto-bot#31]
Hello,

The tweet is surrounded by [ ] as in the screenshot.  I tried many codes but it never changes. What could be the reason for this?

<img width="584" alt="Screenshot 2022-11-23 at 03 07 04" src="https://user-images.githubusercontent.com/32541848/203462064-f606f844-267f-4ce6-8c9c-c1e89b612144.png">
<img width="628" alt="Screenshot 2022-11-23 at 03 07 53" src="https://user-images.githubusercontent.com/32541848/203462121-9165f29d-e105-4a13-b9af-419e6113a0da.png">
`import CryptoBot from './classes';

new CryptoBot('ETH',
{
  hasHashtags: {
    code: true,
    name: true
  },
}
).setTweetInterval({
  hours: 6,
  minutes: 15,
  seconds: 20
})

new CryptoBot('BTC',
{
  hasHashtags: {
    code: true,
    name: true
  },
}
).setTweetInterval({
  hours: 5,
  minutes: 15,
  seconds: 10
})`

**Comment by totigm** [comment]
Hey @trbozo! How are you doing?

Sorry for the delay.

You get your hashtags and dollar symbols surrounded by brackets because the `NODE_ENV` variable is set to `dev`. We did this so devs are able to check how your bot is working without spamming the currency hashtag feed, nor getting replies from bots while just developing.
All you have to do to fix this is update your `NODE_ENV` to `prod` (any other value other than `dev` would work) in your `.env` file, or wherever you store your global variables (or just from the [`config.ts`](https://github.com/totigm/twitter-crypto-bot/blob/v2.0.1/src/config/config.ts#L6) file). 

> If you don't want this to happen while you're developing either, you can just delete the [line 54 at the MessageGenerator class](https://github.com/totigm/twitter-crypto-bot/blob/v2.0.1/src/classes/MessageGenerator.ts#L54):
> ```ts
> if (config.node_env === 'dev') message = message.replace(/\$|#/g, (code) => `[${code}]`);
> ```

If you need anything else just let me know!
